-- Core RAG schema
-- tables:
--   public.roles (canonical role slugs)
--   public.documents (raw text corpus)
--   public.embeddings (vector chunks for documents)

create extension if not exists vector;

create table if not exists public.roles (
  slug text primary key,
  label text not null,
  created_at timestamp with time zone not null default now(),
  constraint roles_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

alter table public.roles enable row level security;

-- Canonical role slug list for retrieval routing.
insert into public.roles (slug, label)
values
  ('software-engineer', 'Software Engineer'),
  ('data-scientist', 'Data Scientist'),
  ('data-engineer', 'Data Engineer'),
  ('product-manager', 'Product Manager'),
  ('project-manager', 'Project Manager'),
  ('ux-designer', 'UX Designer'),
  ('devops-engineer', 'DevOps Engineer'),
  ('qa-engineer', 'QA Engineer')
on conflict (slug) do nothing;

create policy roles_read_authenticated
on public.roles
as permissive
for select
to authenticated
using (true);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  raw_text text not null,
  role_slug text not null references public.roles(slug) on update cascade,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists documents_role_slug_idx on public.documents(role_slug);

alter table public.documents enable row level security;

-- Reference resume corpus is internal-only.
create policy documents_service_role_all
on public.documents
as permissive
for all
to service_role
using (true)
with check (true);

drop trigger if exists trg_documents_set_updated_at on public.documents;
create trigger trg_documents_set_updated_at
before update on public.documents
for each row
execute function public.set_updated_at();

create table if not exists public.embeddings (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  chunk_index integer not null default 0,
  chunk_text text not null,
  embedding vector(1536),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  constraint embeddings_document_chunk_unique unique (document_id, chunk_index)
);

create index if not exists embeddings_document_id_idx on public.embeddings(document_id);

alter table public.embeddings enable row level security;

-- Embeddings are internal-only.
create policy embeddings_service_role_all
on public.embeddings
as permissive
for all
to service_role
using (true)
with check (true);

-- Keep table-level grants explicit so anon/authenticated cannot bypass intent.
revoke all on table public.roles from anon;
revoke all on table public.roles from authenticated;
grant select on table public.roles to authenticated;
grant all on table public.roles to service_role;

revoke all on table public.documents from anon;
revoke all on table public.documents from authenticated;
grant all on table public.documents to service_role;

revoke all on table public.embeddings from anon;
revoke all on table public.embeddings from authenticated;
grant all on table public.embeddings to service_role;
